# Generated by Django 4.0.4 on 2022-06-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_patient_heart_disease_patient_hypertension_and_more'),
        ('Demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.patient', unique=True),
        ),
    ]
