# Generated by Django 4.0.4 on 2022-05-06 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('avg_glucose_level', models.FloatField(blank=True, default=0, null=True)),
                ('bmi', models.FloatField(blank=True, default=0, null=True)),
                ('ever_married', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3)),
                ('smoking_status', models.CharField(choices=[('ex', 'ex fumeur'), ('Actuellement', 'Actuellement fumeur'), ('Jamais', 'Jamais fumeur'), ('Inconnu', 'Inconnu')], default='J', max_length=12)),
                ('stroke', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
