# Generated by Django 4.0.4 on 2022-05-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecine',
            name='Patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(choices=[('ex', 'ex fumeur'), ('Actuellement', 'Actuellement fumeur'), ('Jamais', 'Jamais fumeur'), ('Inconnu', 'Inconnu')], default='Inconnu', max_length=12),
        ),
    ]
