# Generated by Django 4.0.4 on 2022-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_medecine_patients_alter_patient_smoking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecine',
            name='Patients',
        ),
        migrations.AddField(
            model_name='medecine',
            name='Patients',
            field=models.ManyToManyField(null=True, to='Auth.patient'),
        ),
    ]
