# Generated by Django 4.0.4 on 2022-05-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_medecine_patients_medecine_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecine',
            name='Patients',
        ),
        migrations.AddField(
            model_name='medecine',
            name='Patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.patient'),
        ),
    ]
