# Generated by Django 4.0.4 on 2022-05-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_remove_medecine_patients_medecine_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecine',
            name='Patients',
        ),
        migrations.AddField(
            model_name='medecine',
            name='patients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.patient'),
        ),
        migrations.AlterField(
            model_name='medecine',
            name='first_name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='medecine',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecine',
            name='telephone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
