# Generated by Django 4.0.4 on 2022-05-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_remove_medecine_patients_medecine_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecine',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='medecine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.medecine'),
        ),
    ]
