# Generated by Django 4.0.4 on 2022-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_remove_medecine_patients_patient_medecine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstrateur',
            fields=[
                ('username', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
