# Generated by Django 4.0.4 on 2022-05-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_alter_patient_ever_married_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('ex fumeur', 'ex fumeur'), ('Actuellement fumeur', 'Actuellement fumeur'), ('Jamais fumeur', 'Jamais fumeur'), ('Inconnu', 'Inconnu')], default='Inconnu', max_length=19, null=True),
        ),
    ]
