# Generated by Django 4.0.4 on 2022-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_patient_gender_alter_patient_smoking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecine',
            name='postion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
