# Generated by Django 4.0.4 on 2022-05-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_medecine_postion_patient_poids_patient_postion'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heart_disease',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hypertension',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_de_travail',
            field=models.CharField(blank=True, choices=[('gouvernement', 'gouvernement'), ('privé', 'privé'), ('indépendant', 'indépendant'), ('Pas encore', 'Pas encore')], default='Pas encore', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.medecine'),
        ),
    ]
